#include <iostream>

// This is generated by cmake from configured_files/config.hpp.in
#include <internal_use_only/config.hpp>

#define LOG(message) (std::cout << message << std::endl)

int main(int argc, char const *argv[])
{
  // Prints Program name and semver
  std::cout << myproject::cmake::project_name
            << " Version "
            << myproject::cmake::project_version_major
            << "."
            << myproject::cmake::project_version_minor
            << "."
            << myproject::cmake::project_version_patch
            << std::endl;

  return 0;
}
